services:
  homeassistant:
    container_name: HomeAssistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /opt/homeassistant:/config
      - /opt/hass/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220816201023-if00:/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220816201023-if00
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    user: '99'
    environment:
      - TZ=Europe/Amsterdam
    healthcheck:
      test: "mosquitto_sub -E -t '#'"
      interval: 60s
      timeout: 10s
      retries: 5
    volumes:
      - '/opt/mosquitto/config:/mosquitto/config:ro'
      - '/opt/mosquitto/log:/mosquitto/log'
      - '/opt/mosquitto/data:/mosquitto/data'
    ports:
      - '1883:1883'
      - '8883:8883'
    restart: always
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    user: '99'
    volumes:
      - /opt/nodered:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Amsterdam
    restart: always
  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:dev
    healthcheck:
      test: "curl -sf http://localhost:8888"
      interval: 60s
      timeout: 10s
      retries: 5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdaemon:/conf
      # Mount directory of appdaemon apps installed by HACS
      - /opt/homeassistant/appdaemon/apps:/conf/apps/hacs
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - '8888:8888'
    restart: always
