services:
  homeassistant:
    container_name: HomeAssistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /opt/homeassistant:/config
      - /opt/hass/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
      - env_file=/opt/.env
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    environment:
      - TZ=Europe/Amsterdam
      - env_file=/opt/.env
    volumes:
      - /opt/mosquitto:/mosquitto
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
