version: '3.7'

services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: /opt/mosquitto/config/
        target: /mosquitto/config/
      - type: bind
        source: /opt/mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: /opt/mosquitto/data
        target: /mosquitto/data/
    restart: unless-stopped

volumes:
  data:
    name: "mqtt-broker-data"
