services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - “1883:1883”
      - “9001:9001”
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    restart: unless-stopped
