version: '3.7'

services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /opt/mosquitto/config/:/mosquitto/config/
      - /opt/mosquitto/log/:/mosquitto/log/
      - /opt/mosquitto/data:/mosquitto/data/
    restart: unless-stopped

volumes:
  data:
    name: "mqtt-broker-data"
